
# Список служб
services:

  # Запускаем Python приложение из образа Dockerfile
  # Имя службы
  app:
    build:
      # Билдим из текущей директории
      context: .
      args:
        - DEV=true
      # Устанавливаем порты для взаимодействия с контейнером
    ports:
      - "8000:8000"
    volumes:
      # Связываем локальную директорию app с контейнеровским
      # При внесении изменений в Python код, чтобы не перебилдить
      - ./app:/app
      # Команда, которая будет запускать сервис
      # Это будет команда по умолчанию
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"