# Generated by Django 3.2 on 2025-05-08 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250505_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Значение не должно быть меньше 0')], verbose_name='Количество'),
        ),
    ]
