# Generated by Django 3.2 on 2025-05-14 11:51

from django.db import migrations


def migrate_existing_data(apps, schema_editor):
    Recipe = apps.get_model('core', 'Recipe')
    Ingredient = apps.get_model('core', 'Ingredient')
    RecipeIngredient = apps.get_model('core', 'RecipeIngredient')

    for recipe in Recipe.objects.all():
        for ingredient in recipe.ingredients.all():
            RecipeIngredient.objects.create(
                recipe=recipe,
                ingredient=ingredient,
                amount=1,
            )


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20250514_1450'),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_data, reverse_code=migrations.RunPython.noop
        ),
    ]
