---
name: Main

# Триггер для запуска jobs
#on: [push]

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-22.04
    steps:
        # Логинимся в DockerHub для пула образа
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Проверяем, доступен ли сам код проекта
      - name: Checkout
        uses: actions/checkout@v2
        # Запуск юнит-тестов
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
        # Линтер
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"